INSERT INTO enrollment_primary_for_adults_by_department_2022 (department, amount)
VALUES
    ('Guatemala', 4352),
    ('El Progreso', 40),
    ('Sacatepéquez', 180),
    ('Chimaltenango', 83),
    ('Escuintla', 384),
    ('Santa Rosa', 40),
    ('Sololá', 187),
    ('Totonicapán', 33),
    ('Quetzaltenango', 248),
    ('Suchitepéquez', 102),
    ('Retalhuleu', 105),
    ('San Marcos', 279),
    ('Huehuetenango', 116),
    ('Quiché', 149),
    ('Baja Verapaz', 78),
    ('Alta Verapaz', 230),
    ('Petén', 71),
    ('Izabal', 195),
    ('Zacapa', 57),
    ('Chiquimula', 193),
    ('Jalapa', 85),
    ('Jutiapa', 66);